# Generated by Django 2.2.5 on 2019-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191023_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
